.TH "D:/Projects/Stm32/IAR/testMorion/initAll.c" 3 "Вт 9 Фев 2021" "Version 1.0.0" "testMorion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/Stm32/IAR/testMorion/initAll.c
.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x\&.h'\fP
.br
\fC#include 'stm32f10x_dma\&.h'\fP
.br
\fC#include 'stm32f10x_gpio\&.h'\fP
.br
\fC#include 'stm32f10x_usart\&.h'\fP
.br
\fC#include 'stm32f10x_rcc\&.h'\fP
.br
\fC#include 'stm32f10x_tim\&.h'\fP
.br
\fC#include 'stm32f10x_iwdg\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBinitAll\fP ()"
.br
.in -1c
.SH "Функции"
.PP 
.SS "void initAll ()"

.SH "Автор"
.PP 
Автоматически создано Doxygen для testMorion из исходного текста\&.
