.TH "D:/Projects/Stm32/IAR/testMorion/platform_config.h" 3 "Ср 10 Фев 2021" "Version 1.0.0" "testMorion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/Stm32/IAR/testMorion/platform_config.h
.SH SYNOPSIS
.br
.PP
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBUSART1_GPIO\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBUSART1_CLK\fP   RCC_APB2Periph_USART1"
.br
.ti -1c
.RI "#define \fBUSART1_GPIO_CLK\fP   RCC_APB2Periph_GPIOA"
.br
.ti -1c
.RI "#define \fBUSART1_RxPin\fP   GPIO_Pin_10"
.br
.ti -1c
.RI "#define \fBUSART1_TxPin\fP   GPIO_Pin_9"
.br
.ti -1c
.RI "#define \fBUSART1_Tx_DMA_Channel\fP   DMA1_Channel4"
.br
.ti -1c
.RI "#define \fBUSART1_Tx_DMA_FLAG\fP   DMA1_FLAG_TC4"
.br
.ti -1c
.RI "#define \fBUSART1_Rx_DMA_Channel\fP   DMA1_Channel5"
.br
.ti -1c
.RI "#define \fBUSART1_Rx_DMA_FLAG\fP   DMA1_FLAG_TC5"
.br
.ti -1c
.RI "#define \fBUSART1_DR_Base\fP   0x40013804"
.br
.ti -1c
.RI "#define \fBUSB_DISCONNECT\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBUSB_DISCONNECT_PIN\fP   GPIO_Pin_5"
.br
.ti -1c
.RI "#define \fBUSB_DISCONNECT_LOG1\fP   DISABLE"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIO_DISCONNECT\fP   RCC_APB2Periph_GPIOB"
.br
.ti -1c
.RI "#define \fBLED1\fP   0"
.br
.ti -1c
.RI "#define \fBLED1_GPIO_PORT\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBLED1_GPIO_CLK\fP   RCC_APB2Periph_GPIOA"
.br
.ti -1c
.RI "#define \fBLED1_GPIO_PIN\fP   GPIO_Pin_13"
.br
.ti -1c
.RI "#define \fBUSE_USART1_DEFAULT_PA9_PA10\fP"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define LED1   0"

.SS "#define LED1_GPIO_CLK   RCC_APB2Periph_GPIOA"

.SS "#define LED1_GPIO_PIN   GPIO_Pin_13"

.SS "#define LED1_GPIO_PORT   GPIOA"

.SS "#define RCC_APB2Periph_GPIO_DISCONNECT   RCC_APB2Periph_GPIOB"

.SS "#define USART1_CLK   RCC_APB2Periph_USART1"

.SS "#define USART1_DR_Base   0x40013804"

.SS "#define USART1_GPIO   GPIOA"

.SS "#define USART1_GPIO_CLK   RCC_APB2Periph_GPIOA"

.SS "#define USART1_Rx_DMA_Channel   DMA1_Channel5"

.SS "#define USART1_Rx_DMA_FLAG   DMA1_FLAG_TC5"

.SS "#define USART1_RxPin   GPIO_Pin_10"

.SS "#define USART1_Tx_DMA_Channel   DMA1_Channel4"

.SS "#define USART1_Tx_DMA_FLAG   DMA1_FLAG_TC4"

.SS "#define USART1_TxPin   GPIO_Pin_9"

.SS "#define USB_DISCONNECT   GPIOB"

.SS "#define USB_DISCONNECT_LOG1   DISABLE"

.SS "#define USB_DISCONNECT_PIN   GPIO_Pin_5"

.SS "#define USE_USART1_DEFAULT_PA9_PA10"

.SH "Автор"
.PP 
Автоматически создано Doxygen для testMorion из исходного текста\&.
